name: CI on x86_64 linux

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: php version to compile
        default: '8.2'
        type: choice
        options:
          - '8.2'
          - '8.1'
          - '8.0'
          - '7.4'
      build-cli:
        description: build cli binary
        default: true
        type: boolean
      build-micro:
        description: build phpmicro binary
        type: boolean
      build-fpm:
        description: build fpm binary
        type: boolean
      extensions:
        description: extensions to compile (comma separated)
        required: true
        type: string
      debug:
        type: boolean

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: build ${{ inputs.version }} on Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Ubuntu missing packages and mark os suffix
      - run: |
          sudo apt install musl-tools -y
          echo "SPC_BUILD_OS=linux" >> $GITHUB_ENV

      # Cache composer dependencies
      - id: cache-composer-deps
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-dependencies

      # If there's no Composer cache, install dependencies
      - if: steps.cache-composer-deps.outputs.cache-hit != 'true'
        run: composer update --no-dev

      # Cache downloaded source
      - id: cache-download
        uses: actions/cache@v3
        with:
          path: downloads
          key: php-${{ inputs.version }}-dependencies

      # With or without debug
      - if: inputs.debug == true
        run: echo "SPC_BUILD_DEBUG=--debug" >> $GITHUB_ENV

      # With target select: cli, micro or both
      - if: ${{ inputs.build-cli == true }}
        run: echo "SPC_BUILD_CLI=--build-cli" >> $GITHUB_ENV
      - if: ${{ inputs.build-micro == true }}
        run: echo "SPC_BUILD_MICRO=--build-micro" >> $GITHUB_ENV
      - if: ${{ inputs.build-fpm == true }}
        run: echo "SPC_BUILD_FPM=--build-fpm" >> $GITHUB_ENV

      # If there's no dependencies cache, fetch sources, with or without debug
      - if: steps.cache-download.outputs.cache-hit != 'true'
        run: CACHE_API_EXEC=yes ./bin/spc-alpine-docker download --with-php=${{ inputs.version }} --all ${{ env.SPC_BUILD_DEBUG }}

      # Run build command
      - run: ./bin/spc-alpine-docker build ${{ inputs.extensions }} ${{ env.SPC_BUILD_DEBUG }} ${{ env.SPC_BUILD_CLI }} ${{ env.SPC_BUILD_MICRO }} ${{ env.SPC_BUILD_FPM }}

      - name: Pack PHP ${{ inputs.version }} to archive
        run: |
          PHPVER=$(cat source/php-src/main/php_version.h | grep "PHP_VERSION " | awk -F\" '{print $2}')
          mkdir dist/
          tar -zcvf "dist/php-$PHPVER-cli-linux-x86_64.tar.gz" -C buildroot/bin/ ./php
          if [ -f "./buildroot/bin/micro.sfx" ]; then
            tar -zcvf "dist/php-$PHPVER-micro-linux-x86_64.tar.gz" -C buildroot/bin/ ./micro.sfx
          fi
          if [ -f "./buildroot/bin/php-fpm" ]; then
            tar -zcvf "dist/php-$PHPVER-fpm-linux-x86_64.tar.gz" -C buildroot/bin/ ./php-fpm
          fi
      - name: Deploy to Zhamao Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SERVER_SECRET_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.DEPLOY_SERVER_PORT }}
          REMOTE_USER: ${{ secrets.DEPLOY_SERVER_USER }}
          TARGET: ${{ secrets.DEPLOY_SERVER_TARGET }}
